/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 earth.gltf
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/earth-63d902b12fd14868b4dc2f19dc21d7c2
Title: Earth
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GroupProps, useFrame } from '@react-three/fiber';
import { Mesh, BufferGeometry, Material } from 'three';

const Earth = (props: GroupProps) => {
  const { nodes, materials } = useGLTF('/earth.gltf');
  const meshRef = useRef<Mesh<BufferGeometry, Material | Material[]>>(null);

  useFrame(() => {
    if (meshRef.current) {
      meshRef.current.rotation.x = meshRef.current.rotation.y += 0.01;
    }
  });

  console.log('nodes: ', nodes);
  return (
    <mesh position={[0, 0, 0]} ref={meshRef}>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group scale={2.5}>
              <mesh geometry={(nodes.Object_2 as any).geometry} material={materials.moon} />
            </group>
          </group>
        </group>
      </group>
    </mesh>
  );
};

export default Earth;

useGLTF.preload('/earth.gltf');
